document.writeln("<style type=\"text/css\">");

document.writeln(".tel_left{ width:280px; float:left; overflow:hidden;}");
document.writeln(".tel_left div{ height:110px; position:relative; background:#F9FAF9; border-top:1px solid #E9EAE7; border-right:2px solid #5D5E5D;}");
document.writeln(".tel_left div.tel_01{ background:#FFF; border-right:0;}");
document.writeln(".tel_left div.tel_01 dt{ background:#E50210;}");
document.writeln(".tel_left div dt{ width:70px; height:70px; float:left; font-size:18px; line-height:30px; text-align:center; background:#BCBDBC; color:#FFF; border-radius:50px; margin-right:15px; position:relative;}");
document.writeln(".tel_left #b_0 dt{ line-height:70px;}");
document.writeln(".tel_left div dd{ line-height:20px;}");
document.writeln(".tel_left #b_0 dd,.tel_left #c_0 dd{ padding-top:12px;}");
document.writeln(".tel_left #d_0 dd{ padding-top:20px;}");
document.writeln(".tel_left div dd span{ margin-left:12px; display:inline-block;}");
document.writeln(".tel_left dl{ padding:20px 10px;}");
document.writeln("");
document.writeln(".tel_right{ width:880px; float:right; margin:15px 15px 0 0;}");
document.writeln(".tel_right td{ padding:0 15px; line-height:30px;}");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</style>");
document.writeln("<div class=\"tel_tit\"></div>");
document.writeln("<div class=\"tel_box\">");
document.writeln("  <div class=\"tel_left\">");
document.writeln("    <div id=\"a_0\" class=\"tel_01\" style=\"border-top:0;\">");
document.writeln("      <dl>");
document.writeln("        <dt style=\"line-height:24px; padding-top:10px; height:60px;\">东北<br />华北<span class=\"arrow-right\"></span></dt><dd><span>北京</span><span>天津</span><span>青岛</span><span>河北</span><span>山西</span><span>内蒙古</span><span>黑龙江</span><span>沈阳</span><span>吉林</span><span>大连</span></dd>");
document.writeln("      </dl>");
document.writeln("    </div>");
document.writeln("        <div id=\"b_0\">");
document.writeln("      <dl>");
document.writeln("        <dt>华东<span class=\"arrow-right\"></span></dt><dd><span>上海</span><span>苏州</span><span>福建</span><span>江苏</span><span>安徽</span><span>山东</span><span>浙江</span></dd>");
document.writeln("      </dl>");
document.writeln("    </div>");
document.writeln("        <div id=\"c_0\">");
document.writeln("      <dl>");
document.writeln("        <dt style=\"line-height:24px; padding-top:10px; height:60px;\">华中<br />华西<span class=\"arrow-right\"></span></dt><dd><span>湖南</span><span>湖北</span><span>四川</span><span>江西</span><span>河南</span><span>重庆</span><span>陕西</span></dd>");
document.writeln("      </dl>");
document.writeln("    </div>");
document.writeln("        <div id=\"d_0\">");
document.writeln("      <dl>");
document.writeln("        <dt style=\"line-height:24px; padding-top:10px; height:60px;\">华南<br />西南<span class=\"arrow-right\"></span></dt><dd><span>广东</span><span>深圳</span><span>云南</span><span>广西</span></dd>");
document.writeln("      </dl>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("<div class=\"tel_right\">");
document.writeln(" <div id=\"a_1\">");
document.writeln(" <table width=\"100%\" border=\"0\" cellspacing=\"1\" cellpadding=\"0\" bgcolor=\"#CCCDCC\" >");
document.writeln("  <tr>");
document.writeln("    <td width=\"12%\" height=\"38\" align=\"center\" bgcolor=\"#FFFFFF\"><strong>省份城市</strong></td>");
document.writeln("    <td width=\"55%\" bgcolor=\"#FFFFFF\"><strong>公司地址</strong></td>");
document.writeln("    <td width=\"33%\" bgcolor=\"#FFFFFF\"><strong>各省电话</strong></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">北  京</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">北京市海淀区黄平路19号院龙旗广场E座16/17层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">010-85659300 /    13910872604</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">天  津</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">天津市河北区迎贤道宁静家园8号楼18层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">022-87584861 / 13920426189</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">青  岛</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">青岛市城阳区黑龙江中路187/189号1栋4层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">0532-80926708 / 13963998532</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">河  北</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">石家庄市裕华区裕华路剑桥春雨12号楼1单元13层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">0311-89627279 / 13931127765</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">山  西</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">太原市小店区长风街131号华德中心广场B座8层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">0351-7226651 / 13934161632</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">内蒙古</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">呼和浩特市赛罕区万达广场B区3号楼一单元8层</td>");
document.writeln("     <td bgcolor=\"#FFFFFF\">0471-3244631    / 15034964602</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">黑龙江</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">哈尔滨市南岗区黄河路99号黄河大厦5层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">0451-51057528 / 13945059552</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">辽  宁</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">沈阳市大东区小东路10-4    大悦城C4座15层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">024-24361087 / 13998131820</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">吉  林</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">长春市朝阳区红旗街万达广场5号楼2单元22层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">0431-89373362 / 13944081328</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">大  连</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">大连市中山区民主广场海景花园25层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">0411-62898112 / 13998697013</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td colspan=\"3\" align=\"right\" bgcolor=\"#FFFFFF\"><b class=\"red\">甘肃、宁夏、青海、西藏、新疆———联系北京总部，海南———联系深圳</b></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td colspan=\"3\" bgcolor=\"#EFEEEE\"><b style=\"font-size:16px\">国际订单</b>    韩国客户联系青岛    俄罗斯客户联系哈尔滨    日本客户联系苏州    其它国际客户联系北京总部</td>");
document.writeln("    </tr>");
document.writeln("</table>");
document.writeln("</div>");
document.writeln("<div id=\"b_1\" style=\"display:none\">");
document.writeln(" <table width=\"100%\" border=\"0\" cellspacing=\"1\" cellpadding=\"0\" bgcolor=\"#CCCDCC\" >");
document.writeln("  <tr>");
document.writeln("    <td width=\"12%\" height=\"38\" align=\"center\" bgcolor=\"#FFFFFF\"><strong>省份城市</strong></td>");
document.writeln("    <td width=\"55%\" bgcolor=\"#FFFFFF\"><strong>公司地址</strong></td>");
document.writeln("    <td width=\"33%\" bgcolor=\"#FFFFFF\"><strong>各省电话</strong></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">上  海</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">上海市闵行区立跃路2995号百灵商务中心1号楼3层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">021-60643088/13817925946</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">苏  州</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">苏州市高新区滨河路588号赛格3期3层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">0512-68056253/13915586553</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">福  建</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">福州市仓山区仓山万达广场B1区B1座10层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">0591-83852705/13959113847</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">江  苏</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">南京市建邺区扬子江大道399号海峡城A4栋2层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">025-86677326/13914758293</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">安  徽</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">合肥市蜀山区肥西路58号兴科大厦10层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">0551-63631355/13956935102</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">山  东</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">济南市天桥区清河北路紫金山儿童城道格拉斯大厦21层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">0531-82926206/13969015606</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">浙  江</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">杭州市滨江区江汉路1786号钱龙大厦14层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">0571-88141586/13968122958</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td colspan=\"3\" align=\"right\" bgcolor=\"#FFFFFF\" height=\"123\"><b class=\"red\">甘肃、宁夏、青海、西藏、新疆———联系北京总部，海南———联系深圳</b></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td colspan=\"3\" bgcolor=\"#EFEEEE\"><b style=\"font-size:16px\">国际订单</b>    韩国客户联系青岛    俄罗斯客户联系哈尔滨    日本客户联系苏州    其它国际客户联系北京总部</td>");
document.writeln("    </tr>");
document.writeln("</table>");
document.writeln("</div>");
document.writeln("<div id=\"c_1\" style=\"display:none\">");
document.writeln(" <table width=\"100%\" border=\"0\" cellspacing=\"1\" cellpadding=\"0\" bgcolor=\"#CCCDCC\" >");
document.writeln("  <tr>");
document.writeln("    <td width=\"12%\" height=\"38\" align=\"center\" bgcolor=\"#FFFFFF\"><strong>省份城市</strong></td>");
document.writeln("    <td width=\"55%\" bgcolor=\"#FFFFFF\"><strong>公司地址</strong></td>");
document.writeln("    <td width=\"33%\" bgcolor=\"#FFFFFF\"><strong>各省电话</strong></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">湖  南</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">长沙市芙蓉区远大一路280号湘域相遇北栋9层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">0731-82096858 / 13973140779</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">湖  北</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">武汉市东西湖区金银湖南街金珠港湾一期3-5-1栋</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\"> 027-85518995 / 13627295341</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">江  西</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">南昌市青云谱区京山北路玉带明珠19栋2单元3层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">0791-85212484 / 13979165171</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">河  南</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">郑州市管城区未来路升龙玺园4号楼3层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">0371-53393891 / 13939027823</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">四  川</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">成都市成华区双林路388号富临大厦22层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">028-83525260 / 13980713834</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">重  庆</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">重庆市沙坪坝区三峡广场天陈路16号天安大厦19层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">023-65818655 / 18725663432</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">陕  西</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">西安市碑林区东关正街129号世贸大厦C座21层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">029-89532861 / 13991262568</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td colspan=\"3\" align=\"right\" height=\"123\" bgcolor=\"#FFFFFF\"><b class=\"red\">甘肃、宁夏、青海、西藏、新疆———联系北京总部，海南———联系深圳</b></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td colspan=\"3\" bgcolor=\"#EFEEEE\"><b style=\"font-size:16px\">国际订单</b>    韩国客户联系青岛    俄罗斯客户联系哈尔滨    日本客户联系苏州    其它国际客户联系北京总部</td>");
document.writeln("    </tr>");
document.writeln("</table>");
document.writeln("</div>");
document.writeln("<div id=\"d_1\" style=\"display:none\">");
document.writeln("  <table width=\"100%\" border=\"0\" cellspacing=\"1\" cellpadding=\"0\" bgcolor=\"#CCCDCC\" >");
document.writeln("  <tr>");
document.writeln("    <td width=\"12%\" height=\"38\" align=\"center\" bgcolor=\"#FFFFFF\"><strong>省份城市</strong></td>");
document.writeln("    <td width=\"55%\" bgcolor=\"#FFFFFF\"><strong>公司地址</strong></td>");
document.writeln("    <td width=\"33%\" bgcolor=\"#FFFFFF\"><strong>各省电话</strong></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">广  东</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">广州市天河区元岗中横街1号天河慧通产业广场A1栋一层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">020-85262121/13925029253</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">深圳</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">深圳龙华新区清祥路23号德信昌大厦6层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">0755-23303995/13923801467</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">云  南</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">昆明市官渡区金源大道茗春苑3栋1单元2层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">0871-63588894 / 15812099743</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\" bgcolor=\"#FFFFFF\">广  西</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">南宁市西乡塘区永和路2号汇百嘉商业广场1单元10层</td>");
document.writeln("    <td bgcolor=\"#FFFFFF\">0771-6771246 / 13657818474</td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td colspan=\"3\" align=\"right\"  height=\"216\" bgcolor=\"#FFFFFF\"><b class=\"red\">甘肃、宁夏、青海、西藏、新疆———联系北京总部，海南———联系深圳</b></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td colspan=\"3\" bgcolor=\"#EFEEEE\"><b style=\"font-size:16px\">国际订单</b>    韩国客户联系青岛    俄罗斯客户联系哈尔滨    日本客户联系苏州    其它国际客户联系北京总部</td>");
document.writeln("    </tr>");
document.writeln("</table>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");


   function switchmodTag(){
    }
    switchmodTag.prototype = {
    st : function(menus,divs,openClass,closeClass){
    var _this = this;
    if(menus.length != divs.length)
    {
    alert("菜单层和内容层数量不一样!");
    return false;
    }
    for(var i = 0 ; i < menus.length ; i++)
    {
    _this.$(menus[i]).value = i;
    _this.$(menus[i]).onmouseover = function(){
    for(var j = 0 ; j < menus.length ; j++)
    {
    _this.$(menus[j]).className = closeClass;
    _this.$(divs[j]).style.display = "none";
    }
    _this.$(menus[this.value]).className = openClass;
    _this.$(divs[this.value]).style.display = "block";
    }
    }
    },
    $ : function(oid){
    if(typeof(oid) == "string")
    return document.getElementById(oid);
    return oid;
    }
    }
    window.onload = function(){
    var STmodel = new switchmodTag();
	    STmodel.st(["a_0","b_0","c_0","d_0"],["a_1","b_1","c_1","d_1"],"tel_01","tel_02");
	 STmodel.st(["a","b","c","d","e","f","g","h","i"],["a1","b1","c1","d1","e1","f1","g1","h1","i1"],"st01","st02");
	STmodel.st(["aa","bb","cc","dd","ee","ff","gg","hh","ii"],["aa1","bb1","cc1","dd1","ee1","ff1","gg1","hh1","ii1"],"st01","st02");
	STmodel.st(["aaa","bbb","ccc","ddd","eee","fff","ggg","hhh","iii","jjj"],["aaa1","bbb1","ccc1","ddd1","eee1","fff1","ggg1","hhh1","iii1","jjj1"],"st01","st02");

    }